### ISSUE TITLE
상세페이지 기능구현

### ISSUE THREAD

**Issue by Rose-Rosie-Rose** [DongneMashil/dongnemashil-fe#3]

**Comment by taehyunkim3** [comment]
api 확정 및 로그인 연계 테스트, 디자인 확정이 필요합니다.

**Comment by taehyunkim3** [comment]
로그인 토큰-> 댓글작성, 좋아요 기능 테스트, 
상세페이지 isLiked 값 어떻게 오는지 여부 확정이 필요합니다 .
